# Generated by Django 2.1.7 on 2019-02-23 22:25

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('surname', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_client', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('key', models.CharField(blank=True, max_length=120, null=True)),
                ('activated', models.BooleanField(default=False)),
                ('forced_expired', models.BooleanField(default=False)),
                ('expires', models.IntegerField(default=7)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('passport', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_image_path)),
                ('sex', models.CharField(blank=True, choices=[('s', 'SEX'), ('m', 'MALE'), ('f', 'FEMALE')], default='s', max_length=7, null=True)),
                ('interest', models.CharField(blank=True, choices=[('m', 'MALE'), ('f', 'FEMALE'), ('b', 'MALE & FEMALE')], default='m', max_length=18, null=True)),
                ('marital', models.CharField(blank=True, choices=[('si', 'SINGLE'), ('ma', 'MARRIED'), ('di', 'DIVORCED'), ('se', 'SEPERATED')], max_length=18, null=True)),
                ('kids', models.CharField(blank=True, choices=[('no', 'NO'), ('yes', 'YES'), ('maybe', 'MAYBE')], max_length=5, null=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('DOB', models.DateField(blank=True, help_text='year-month-day', max_length=8, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number must start with "+123" or any internationalize country code', max_length=128, null=True)),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact fax number', max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('zip_code', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
                ('state_province', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('SSN', localflavor.us.models.USSocialSecurityNumberField(blank=True, help_text='format: xxx-xx-xxxx (only applies to US Citizens', max_length=11, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
